openstack_client:
  auth:
    auth_url: "http://<openstack_controller_address>/identity/v3"
    username: "admin"
    password: <password>
    project_name: "demo"
    user_domain_id: "default"
    project_domain_id: "default"

  vnf:
    # openstack image id that all vnfs will be built from
    base_image_id: "3f949162-d954-4946-920c-76394e580802"
    # each vnfs connect two openstack networks, data network and management network
    data_net_id: "a32834f4-e7d5-4359-bd1a-6d7efaf26a79"
    mgmt_net_id: "7585f346-e25b-442b-803a-6d878839dfd6"
