openstack_client:
  auth:
    auth_url: "http://192.168.3.11/identity/v3"
    username: "admin"
    password: <password>
    project_name: "demo"
    user_domain_id: "default"
    project_domain_id: "default"

  vnf:
    # each vnfs connect two openstack networks, data network and management network
    data_net_id: "e11bc4ac-ad69-4b84-a973-87d844dd4367"
    mgmt_net_id: "624971d6-7374-4536-a1ae-8377f91d73d6"
