swagger: "2.0"
info:
  description: "AI module service for the NI project."
  version: "1.0.0"
  title: "AI Module Service"
host: "localhost:8080"
basePath: "/v2"
tags:
- name: "ai_module"
  description: "Perform management decisions using ML algorithms."
schemes:
- "http"
paths:
  /sfcr_event:
    post:
      tags:
      - "ai_module"
      summary: "Notify AI module of SFC request arrival / departure event."
      description: ""
      operationId: "sfcrEvent"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "Success."
definitions:
  VNFType:
    type: "object"
    properties:
      name:
        type: "string"
      capacity:
        type: "integer"
        format: "int32"
      delay:
        type: "integer"
        format: "int32"
      n_cores:
        type: "integer"
        format: "int32"
      ram:
        type: "integer"
        format: "int32"
  SFCR:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      arrivaltime:
        type: "string"
        format: "date-time"
      src_ip:
        type: "string"
      dst_ip:
        type: "string"
      src_port:
        type: "integer"
        format: "int32"
      dst_port:
        type: "integer"
        format: "int32"
      bw:
        type: "integer"
        format: "int32"
      delay:
        type: "integer"
        format: "int32"
      duration:
        type: "integer"
        format: "int32"
      proto:
        type: "string"
      nf_chain:
        type: "array"
        items:
          type: "string"
  Node:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      ip:
        type: "string"
      n_cores:
        type: "integer"
        format: "int32"
      core_frequency:
        type: "integer"
        format: "int32"
      ram:
        type: "integer"
        format: "int32"
      ram_frequency:
        type: "integer"
        format: "int32"
  Link:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      node1_id:
        type: "integer"
        format: "int64"
      node2_id:
        type: "integer"
        format: "int64"
      delay:
        type: "integer"
        format: "int32"
      bw:
        type: "integer"
        format: "int32"
  Topology:
    type: "object"
    properties:
      node_list:
        type: "array"
        items:
          type: "integer"
          format: "int64"
      edge_list:
        type: "array"
        items:
          type: "integer"
          format: "int64"
  MonitoringEntry:
    type: "object"
    properties:
      timestamp:
        type: "string"
        format: "date-time"
      component_type:
        type: "string"
      component_id:
        type: "integer"
        format: "int64"
      measurement_type:
        type: "string"
      measurement_value:
        type: "number"
        format: "double"
  VNFInstance:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      type:
        $ref: '#/definitions/VNFType'
      node_id:
        type: "integer"
        format: "int64"
      ip:
        type: "string"
  Assignment:
    description: "Mapping between an SFCR and a list of VNF instances."
    type: "object"
    properties:
      sfcr_id:
        type: "integer"
        format: "int64"
      vnf_instace_ids:
        type: "array"
        items:
          type: "integer"
          format: "int64"
  Route:
    description: "Detailed routing information for a given SFCR ID."
    type: "object"
    properties:
      sfcr_id:
        type: "integer"
        format: "int64"
      hops:
        type: "array"
        items:
          type: "object"
          properties:
            type:
              description: "Node or VNFInstance."
              type: "string"
            id:
              type: "integer"
              format: ":int64"
externalDocs:
  description: "Find out more about DPNM NI."
  url: "http://dpnm.postech.ac.kr/"