swagger: "2.0"
info:
  description: "NFVO module service for the NI project."
  version: "1.0.0"
  title: "NFVO Module Service"
host: "localhost:8080"
basePath: "/v2"
tags:
- name: "nfvo_module"
  description: "Provides interfaces to the main functionalities and data of the Tacker NFVO."
schemes:
- "http"
paths:
  /sfcr:
    post:
      tags:
      - "sfcr"
      summary: "Add new SFC request."
      description: ""
      operationId: "addSFCR"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "SFC request object to be added."
        required: true
        schema:
          $ref: "#/definitions/SFCR"
      responses:
        200:
          description: "Success."
        400:
          description: "Invalid SFC request parameters supplied."
        405:
          description: "Invalid input."
  /topology:
    get:
      tags:
      - "info"
      summary: "Get current topology information."
      description: ""
      operationId: "getTopology"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "Success."
          schema:
            $ref: "#/definitions/Topology"
  /placement:
    get:
      tags:
      - "info"
      summary: "Get current placement information, i.e., list of all active VNF instances including their location."
      description: ""
      operationId: "getPlacement"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "Success."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/VNFInstance"
  /routes:
    get:
      tags:
      - "info"
      summary: "Get current route information, i.e., list of all active SFCRs including their paths."
      description: ""
      operationId: "getRoutes"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "Success."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Route"
  /requests:
    get:
      tags:
      - "info"
      summary: "Get currently active SFC requests."
      description: ""
      operationId: "getRequests"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "Success."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/SFCR"
  /vnfflavors:
    get:
      tags:
      - "info"
      summary: "Get available VNF flavors."
      description: ""
      operationId: "getVNFFlavors"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "Success."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/VNFFlavor"
definitions:
  VNFType:
    type: "object"
    properties:
      name:
        type: "string"
      capacity:
        type: "integer"
        format: "int32"
      delay:
        type: "integer"
        format: "int32"
      n_cores:
        type: "integer"
        format: "int32"
      ram:
        type: "integer"
        format: "int32"
  SFCR:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      arrivaltime:
        type: "string"
        format: "date-time"
      src_ip:
        type: "string"
      dst_ip:
        type: "string"
      src_port:
        type: "integer"
        format: "int32"
      dst_port:
        type: "integer"
        format: "int32"
      bw:
        type: "integer"
        format: "int32"
      delay:
        type: "integer"
        format: "int32"
      duration:
        type: "integer"
        format: "int32"
      proto:
        type: "string"
      nf_chain:
        type: "array"
        items:
          type: "string"
  Node:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      ip:
        type: "string"
      n_cores:
        type: "integer"
        format: "int32"
      core_frequency:
        type: "integer"
        format: "int32"
      ram:
        type: "integer"
        format: "int32"
      ram_frequency:
        type: "integer"
        format: "int32"
  Link:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      node1_id:
        type: "integer"
        format: "int64"
      node2_id:
        type: "integer"
        format: "int64"
      delay:
        type: "integer"
        format: "int32"
      bw:
        type: "integer"
        format: "int32"
  Topology:
    type: "object"
    properties:
      node_list:
        type: "array"
        items:
          type: "integer"
          format: "int64"
      edge_list:
        type: "array"
        items:
          type: "integer"
          format: "int64"
  MonitoringEntry:
    type: "object"
    properties:
      timestamp:
        type: "string"
        format: "date-time"
      component_type:
        type: "string"
      component_id:
        type: "integer"
        format: "int64"
      measurement_type:
        type: "string"
      measurement_value:
        type: "number"
        format: "double"
  VNFInstance:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      type:
        $ref: '#/definitions/VNFType'
      node_id:
        type: "integer"
        format: "int64"
      ip:
        type: "string"
  Assignment:
    description: "Mapping between an SFCR and a list of VNF instances."
    type: "object"
    properties:
      sfcr_id:
        type: "integer"
        format: "int64"
      vnf_instace_ids:
        type: "array"
        items:
          type: "integer"
          format: "int64"
  Route:
    description: "Detailed routing information for a given SFCR ID."
    type: "object"
    properties:
      sfcr_id:
        type: "integer"
        format: "int64"
      hops:
        type: "array"
        items:
          type: "object"
          properties:
            type:
              description: "Node or VNFInstance."
              type: "string"
            id:
              type: "integer"
              format: ":int64"
  VNFFlavor:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
      capacity_mbps:
        type: "integer"
        format: "int32"
      delay_us:
        type: "integer"
        format: "int32"
      n_cores:
        type: "integer"
        format: "int32"
      ram_mb:
        type: "integer"
        format: "int32"
    example:
      n_cores: 1
      ram_mb: 5
      capacity_mbps: 0
      name: "name"
      id: "id"
      delay_us: 6
externalDocs:
  description: "Find out more about DPNM NI."
  url: "http://dpnm.postech.ac.kr/"