# coding: utf-8

"""
    AI Module Service

    AI module service for the NI project.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.monitoring_entry import MonitoringEntry  # noqa: E501
from swagger_client.rest import ApiException


class TestMonitoringEntry(unittest.TestCase):
    """MonitoringEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMonitoringEntry(self):
        """Test MonitoringEntry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.monitoring_entry.MonitoringEntry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
