# coding: utf-8

"""
    NFVO Module Service

    NFVO module service for the NI project.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client_nfvo.models.vnf_flavor import VNFFlavor  # noqa: F401,E501


class Body(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'flavor': 'VNFFlavor',
        'node': 'int'
    }

    attribute_map = {
        'flavor': 'flavor',
        'node': 'node'
    }

    def __init__(self, flavor=None, node=None):  # noqa: E501
        """Body - a model defined in Swagger"""  # noqa: E501

        self._flavor = None
        self._node = None
        self.discriminator = None

        if flavor is not None:
            self.flavor = flavor
        if node is not None:
            self.node = node

    @property
    def flavor(self):
        """Gets the flavor of this Body.  # noqa: E501


        :return: The flavor of this Body.  # noqa: E501
        :rtype: VNFFlavor
        """
        return self._flavor

    @flavor.setter
    def flavor(self, flavor):
        """Sets the flavor of this Body.


        :param flavor: The flavor of this Body.  # noqa: E501
        :type: VNFFlavor
        """

        self._flavor = flavor

    @property
    def node(self):
        """Gets the node of this Body.  # noqa: E501


        :return: The node of this Body.  # noqa: E501
        :rtype: int
        """
        return self._node

    @node.setter
    def node(self, node):
        """Sets the node of this Body.


        :param node: The node of this Body.  # noqa: E501
        :type: int
        """

        self._node = node

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
