---
swagger: "2.0"
info:
  description: "NFVO module service for the NI project."
  version: "1.0.0"
  title: "NFVO Module Service"
basePath: "/v2"
tags:
- name: "nfvo_module"
  description: "Provides interfaces to the main functionalities and data of the Tacker\
    \ NFVO."
schemes:
- "http"
paths:
  /sfcr:
    post:
      tags:
      - "sfcr"
      summary: "Add new SFC request."
      description: ""
      operationId: "add_sfcr"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "SFC request object to be added."
        required: true
        schema:
          $ref: "#/definitions/SFCR"
      responses:
        200:
          description: "Success."
        400:
          description: "Invalid SFC request parameters supplied."
      x-swagger-router-controller: "nfvo_server.controllers.sfcr_controller"
  /routes:
    get:
      tags:
      - "info"
      summary: "Get current route information, i.e., list of all active SFCRs including\
        \ their paths."
      description: ""
      operationId: "get_routes"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Success."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Route"
      x-swagger-router-controller: "nfvo_server.controllers.info_controller"
  /requests:
    get:
      tags:
      - "info"
      summary: "Get currently active SFC requests."
      description: ""
      operationId: "get_requests"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Success."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/SFCR"
      x-swagger-router-controller: "nfvo_server.controllers.info_controller"
  /deploy:
    post:
      tags:
      - "actions"
      summary: "Instantiate an instance of a VNF flavor on a given node."
      description: ""
      operationId: "deploy_vnf"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Flavor of VNF instance to be deployed as well as the target\
          \ node. vnf_name is optional"
        required: true
        schema:
          $ref: "#/definitions/body"
      responses:
        200:
          description: "Success."
          schema:
            type: "string"
        400:
          description: "Invalid parameters supplied."
      x-swagger-router-controller: "nfvo_server.controllers.actions_controller"
  /shutdown:
    post:
      tags:
      - "actions"
      summary: "Shut down a VNF instance."
      description: ""
      operationId: "shutdown_vnf"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "ID of VNF instance to be shut down."
        required: true
        schema:
          $ref: "#/definitions/Shutdown"
      responses:
        200:
          description: "Success."
        400:
          description: "Invalid parameters supplied."
      x-swagger-router-controller: "nfvo_server.controllers.actions_controller"
  /setRoute:
    post:
      tags:
      - "actions"
      summary: "Route a request via the provided route."
      description: ""
      operationId: "set_route"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Route information including SFCR ID and vnf instance ids."
        required: true
        schema:
          $ref: "#/definitions/Route"
      responses:
        200:
          description: "Success."
        400:
          description: "Invalid parameters supplied."
      x-swagger-router-controller: "nfvo_server.controllers.actions_controller"
definitions:
  SFCR:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      arrivaltime:
        type: "string"
        format: "date-time"
      src_ip:
        type: "string"
      dst_ip:
        type: "string"
      src_port:
        type: "integer"
        format: "int32"
      dst_port:
        type: "integer"
        format: "int32"
      bw:
        type: "integer"
        format: "int32"
      delay:
        type: "integer"
        format: "int32"
      duration:
        type: "integer"
        format: "int32"
      proto:
        type: "string"
      nf_chain:
        type: "array"
        items:
          type: "string"
    description: "SFC request. src/dst ip, src/dst port, proto are optional."
    example:
      src_ip: "src_ip"
      src_port: 6
      duration: 2
      delay: 5
      bw: 5
      proto: "proto"
      nf_chain:
      - "nf_chain"
      - "nf_chain"
      arrivaltime: "2000-01-23T04:56:07.000+00:00"
      dst_port: 1
      id: 0
      dst_ip: "dst_ip"
  Route:
    type: "object"
    properties:
      sfc_name:
        type: "string"
      sfcr_id:
        type: "integer"
        format: "int64"
      vnf_instance_ids:
        type: "array"
        items:
          type: "string"
    description: "Detailed routing information for a given SFCR ID. sfc_name is optional"
    example:
      vnf_instance_ids:
      - "vnf_instance_ids"
      - "vnf_instance_ids"
      sfc_name: "sfc_name"
      sfcr_id: 0
  Shutdown:
    type: "object"
    properties:
      vnf_instance_id:
        type: "string"
    description: "vnf instance id to shutdown."
    example:
      vnf_instance_id: "vnf_instance_id"
  body:
    type: "object"
    properties:
      flavor_id:
        type: "string"
      node_name:
        type: "string"
      vnf_name:
        type: "string"
      user_data:
        type: "string"
externalDocs:
  description: "Find out more about DPNM NI."
  url: "http://dpnm.postech.ac.kr/"
