# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nfvo_server.models.base_model_ import Model
from nfvo_server import util


class RouteUpdate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, route_id: str=None, vnf_instance_ids: List[List[str]]=None):  # noqa: E501
        """RouteUpdate - a model defined in Swagger

        :param route_id: The route_id of this RouteUpdate.  # noqa: E501
        :type route_id: str
        :param vnf_instance_ids: The vnf_instance_ids of this RouteUpdate.  # noqa: E501
        :type vnf_instance_ids: List[List[str]]
        """
        self.swagger_types = {
            'route_id': str,
            'vnf_instance_ids': List[List[str]]
        }

        self.attribute_map = {
            'route_id': 'route_id',
            'vnf_instance_ids': 'vnf_instance_ids'
        }

        self._route_id = route_id
        self._vnf_instance_ids = vnf_instance_ids

    @classmethod
    def from_dict(cls, dikt) -> 'RouteUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RouteUpdate of this RouteUpdate.  # noqa: E501
        :rtype: RouteUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def route_id(self) -> str:
        """Gets the route_id of this RouteUpdate.


        :return: The route_id of this RouteUpdate.
        :rtype: str
        """
        return self._route_id

    @route_id.setter
    def route_id(self, route_id: str):
        """Sets the route_id of this RouteUpdate.


        :param route_id: The route_id of this RouteUpdate.
        :type route_id: str
        """

        self._route_id = route_id

    @property
    def vnf_instance_ids(self) -> List[List[str]]:
        """Gets the vnf_instance_ids of this RouteUpdate.

        each sub-list represent a node on the traffic path. each node is a list of vnf instances, where traffic are load-balanced  # noqa: E501

        :return: The vnf_instance_ids of this RouteUpdate.
        :rtype: List[List[str]]
        """
        return self._vnf_instance_ids

    @vnf_instance_ids.setter
    def vnf_instance_ids(self, vnf_instance_ids: List[List[str]]):
        """Sets the vnf_instance_ids of this RouteUpdate.

        each sub-list represent a node on the traffic path. each node is a list of vnf instances, where traffic are load-balanced  # noqa: E501

        :param vnf_instance_ids: The vnf_instance_ids of this RouteUpdate.
        :type vnf_instance_ids: List[List[str]]
        """

        self._vnf_instance_ids = vnf_instance_ids
