# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nfvo_server.models.base_model_ import Model
from nfvo_server import util


class RouteID(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None):  # noqa: E501
        """RouteID - a model defined in Swagger

        :param id: The id of this RouteID.  # noqa: E501
        :type id: str
        """
        self.swagger_types = {
            'id': str
        }

        self.attribute_map = {
            'id': 'id'
        }

        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'RouteID':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RouteID of this RouteID.  # noqa: E501
        :rtype: RouteID
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this RouteID.


        :return: The id of this RouteID.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this RouteID.


        :param id: The id of this RouteID.
        :type id: str
        """

        self._id = id
