# coding: utf-8

# flake8: noqa

"""
    AI Module Service

    AI module service for the NI project.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client_ai.api.ai_module_api import AiModuleApi

# import ApiClient
from swagger_client_ai.api_client import ApiClient
from swagger_client_ai.configuration import Configuration
# import models into sdk package
from swagger_client_ai.models.assignment import Assignment
from swagger_client_ai.models.link import Link
from swagger_client_ai.models.monitoring_entry import MonitoringEntry
from swagger_client_ai.models.node import Node
from swagger_client_ai.models.route import Route
from swagger_client_ai.models.route_hops import RouteHops
from swagger_client_ai.models.sfcr import SFCR
from swagger_client_ai.models.topology import Topology
from swagger_client_ai.models.vnf_instance import VNFInstance
from swagger_client_ai.models.vnf_type import VNFType
