# coding: utf-8

"""
    AI Module Service

    AI module service for the NI project.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Assignment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sfcr_id': 'int',
        'vnf_instace_ids': 'list[int]'
    }

    attribute_map = {
        'sfcr_id': 'sfcr_id',
        'vnf_instace_ids': 'vnf_instace_ids'
    }

    def __init__(self, sfcr_id=None, vnf_instace_ids=None):  # noqa: E501
        """Assignment - a model defined in Swagger"""  # noqa: E501

        self._sfcr_id = None
        self._vnf_instace_ids = None
        self.discriminator = None

        if sfcr_id is not None:
            self.sfcr_id = sfcr_id
        if vnf_instace_ids is not None:
            self.vnf_instace_ids = vnf_instace_ids

    @property
    def sfcr_id(self):
        """Gets the sfcr_id of this Assignment.  # noqa: E501


        :return: The sfcr_id of this Assignment.  # noqa: E501
        :rtype: int
        """
        return self._sfcr_id

    @sfcr_id.setter
    def sfcr_id(self, sfcr_id):
        """Sets the sfcr_id of this Assignment.


        :param sfcr_id: The sfcr_id of this Assignment.  # noqa: E501
        :type: int
        """

        self._sfcr_id = sfcr_id

    @property
    def vnf_instace_ids(self):
        """Gets the vnf_instace_ids of this Assignment.  # noqa: E501


        :return: The vnf_instace_ids of this Assignment.  # noqa: E501
        :rtype: list[int]
        """
        return self._vnf_instace_ids

    @vnf_instace_ids.setter
    def vnf_instace_ids(self, vnf_instace_ids):
        """Sets the vnf_instace_ids of this Assignment.


        :param vnf_instace_ids: The vnf_instace_ids of this Assignment.  # noqa: E501
        :type: list[int]
        """

        self._vnf_instace_ids = vnf_instace_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Assignment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Assignment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
