# coding: utf-8

"""
    AI Module Service

    AI module service for the NI project.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Node(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'ip': 'str',
        'n_cores': 'int',
        'core_frequency': 'int',
        'ram': 'int',
        'ram_frequency': 'int'
    }

    attribute_map = {
        'id': 'id',
        'ip': 'ip',
        'n_cores': 'n_cores',
        'core_frequency': 'core_frequency',
        'ram': 'ram',
        'ram_frequency': 'ram_frequency'
    }

    def __init__(self, id=None, ip=None, n_cores=None, core_frequency=None, ram=None, ram_frequency=None):  # noqa: E501
        """Node - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._ip = None
        self._n_cores = None
        self._core_frequency = None
        self._ram = None
        self._ram_frequency = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if ip is not None:
            self.ip = ip
        if n_cores is not None:
            self.n_cores = n_cores
        if core_frequency is not None:
            self.core_frequency = core_frequency
        if ram is not None:
            self.ram = ram
        if ram_frequency is not None:
            self.ram_frequency = ram_frequency

    @property
    def id(self):
        """Gets the id of this Node.  # noqa: E501


        :return: The id of this Node.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Node.


        :param id: The id of this Node.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def ip(self):
        """Gets the ip of this Node.  # noqa: E501


        :return: The ip of this Node.  # noqa: E501
        :rtype: str
        """
        return self._ip

    @ip.setter
    def ip(self, ip):
        """Sets the ip of this Node.


        :param ip: The ip of this Node.  # noqa: E501
        :type: str
        """

        self._ip = ip

    @property
    def n_cores(self):
        """Gets the n_cores of this Node.  # noqa: E501


        :return: The n_cores of this Node.  # noqa: E501
        :rtype: int
        """
        return self._n_cores

    @n_cores.setter
    def n_cores(self, n_cores):
        """Sets the n_cores of this Node.


        :param n_cores: The n_cores of this Node.  # noqa: E501
        :type: int
        """

        self._n_cores = n_cores

    @property
    def core_frequency(self):
        """Gets the core_frequency of this Node.  # noqa: E501


        :return: The core_frequency of this Node.  # noqa: E501
        :rtype: int
        """
        return self._core_frequency

    @core_frequency.setter
    def core_frequency(self, core_frequency):
        """Sets the core_frequency of this Node.


        :param core_frequency: The core_frequency of this Node.  # noqa: E501
        :type: int
        """

        self._core_frequency = core_frequency

    @property
    def ram(self):
        """Gets the ram of this Node.  # noqa: E501


        :return: The ram of this Node.  # noqa: E501
        :rtype: int
        """
        return self._ram

    @ram.setter
    def ram(self, ram):
        """Sets the ram of this Node.


        :param ram: The ram of this Node.  # noqa: E501
        :type: int
        """

        self._ram = ram

    @property
    def ram_frequency(self):
        """Gets the ram_frequency of this Node.  # noqa: E501


        :return: The ram_frequency of this Node.  # noqa: E501
        :rtype: int
        """
        return self._ram_frequency

    @ram_frequency.setter
    def ram_frequency(self, ram_frequency):
        """Sets the ram_frequency of this Node.


        :param ram_frequency: The ram_frequency of this Node.  # noqa: E501
        :type: int
        """

        self._ram_frequency = ram_frequency

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Node, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Node):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
