# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nfvo_server.models.base_model_ import Model
from nfvo_server.models.vnf_flavor import VNFFlavor  # noqa: F401,E501
from nfvo_server import util


class Body(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, flavor: VNFFlavor=None, node_name: str=None):  # noqa: E501
        """Body - a model defined in Swagger

        :param flavor: The flavor of this Body.  # noqa: E501
        :type flavor: VNFFlavor
        :param node_name: The node_name of this Body.  # noqa: E501
        :type node_name: str
        """
        self.swagger_types = {
            'flavor': VNFFlavor,
            'node_name': str
        }

        self.attribute_map = {
            'flavor': 'flavor',
            'node_name': 'node_name'
        }

        self._flavor = flavor
        self._node_name = node_name

    @classmethod
    def from_dict(cls, dikt) -> 'Body':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body of this Body.  # noqa: E501
        :rtype: Body
        """
        return util.deserialize_model(dikt, cls)

    @property
    def flavor(self) -> VNFFlavor:
        """Gets the flavor of this Body.


        :return: The flavor of this Body.
        :rtype: VNFFlavor
        """
        return self._flavor

    @flavor.setter
    def flavor(self, flavor: VNFFlavor):
        """Sets the flavor of this Body.


        :param flavor: The flavor of this Body.
        :type flavor: VNFFlavor
        """

        self._flavor = flavor

    @property
    def node_name(self) -> str:
        """Gets the node_name of this Body.


        :return: The node_name of this Body.
        :rtype: str
        """
        return self._node_name

    @node_name.setter
    def node_name(self, node_name: str):
        """Sets the node_name of this Body.


        :param node_name: The node_name of this Body.
        :type node_name: str
        """

        self._node_name = node_name
