# coding: utf-8

"""
    NFVO Module Service

    NFVO module service for the NI project.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.info_api import InfoApi  # noqa: E501
from swagger_client.rest import ApiException


class TestInfoApi(unittest.TestCase):
    """InfoApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.info_api.InfoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_placement(self):
        """Test case for get_placement

        Get current placement information, i.e., list of all active VNF instances including their location.  # noqa: E501
        """
        pass

    def test_get_requests(self):
        """Test case for get_requests

        Get currently active SFC requests.  # noqa: E501
        """
        pass

    def test_get_routes(self):
        """Test case for get_routes

        Get current route information, i.e., list of all active SFCRs including their paths.  # noqa: E501
        """
        pass

    def test_get_topology(self):
        """Test case for get_topology

        Get current topology information.  # noqa: E501
        """
        pass

    def test_get_vnf_flavors(self):
        """Test case for get_vnf_flavors

        Get available VNF flavors.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
