# coding: utf-8

# flake8: noqa
"""
    Traffic Generator Service

    Traffic generator service for the NI project.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client_trafgen.models.sfcr import SFCR
from swagger_client_trafgen.models.vnf_type import VNFType
