# coding: utf-8

"""
    Traffic Generator Service

    Traffic generator service for the NI project.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class VNFType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'capacity': 'int',
        'delay': 'int',
        'n_cores': 'int',
        'ram': 'int'
    }

    attribute_map = {
        'name': 'name',
        'capacity': 'capacity',
        'delay': 'delay',
        'n_cores': 'n_cores',
        'ram': 'ram'
    }

    def __init__(self, name=None, capacity=None, delay=None, n_cores=None, ram=None):  # noqa: E501
        """VNFType - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._capacity = None
        self._delay = None
        self._n_cores = None
        self._ram = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if capacity is not None:
            self.capacity = capacity
        if delay is not None:
            self.delay = delay
        if n_cores is not None:
            self.n_cores = n_cores
        if ram is not None:
            self.ram = ram

    @property
    def name(self):
        """Gets the name of this VNFType.  # noqa: E501


        :return: The name of this VNFType.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this VNFType.


        :param name: The name of this VNFType.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def capacity(self):
        """Gets the capacity of this VNFType.  # noqa: E501


        :return: The capacity of this VNFType.  # noqa: E501
        :rtype: int
        """
        return self._capacity

    @capacity.setter
    def capacity(self, capacity):
        """Sets the capacity of this VNFType.


        :param capacity: The capacity of this VNFType.  # noqa: E501
        :type: int
        """

        self._capacity = capacity

    @property
    def delay(self):
        """Gets the delay of this VNFType.  # noqa: E501


        :return: The delay of this VNFType.  # noqa: E501
        :rtype: int
        """
        return self._delay

    @delay.setter
    def delay(self, delay):
        """Sets the delay of this VNFType.


        :param delay: The delay of this VNFType.  # noqa: E501
        :type: int
        """

        self._delay = delay

    @property
    def n_cores(self):
        """Gets the n_cores of this VNFType.  # noqa: E501


        :return: The n_cores of this VNFType.  # noqa: E501
        :rtype: int
        """
        return self._n_cores

    @n_cores.setter
    def n_cores(self, n_cores):
        """Sets the n_cores of this VNFType.


        :param n_cores: The n_cores of this VNFType.  # noqa: E501
        :type: int
        """

        self._n_cores = n_cores

    @property
    def ram(self):
        """Gets the ram of this VNFType.  # noqa: E501


        :return: The ram of this VNFType.  # noqa: E501
        :rtype: int
        """
        return self._ram

    @ram.setter
    def ram(self, ram):
        """Sets the ram of this VNFType.


        :param ram: The ram of this VNFType.  # noqa: E501
        :type: int
        """

        self._ram = ram

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VNFType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VNFType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
