# coding: utf-8

"""
    NFVO Module Service

    NFVO module service for the NI project.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.info_api import InfoApi  # noqa: E501
from swagger_client.rest import ApiException


class TestInfoApi(unittest.TestCase):
    """InfoApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.info_api.InfoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_topology(self):
        """Test case for get_topology

        Get current topology information.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
