# coding: utf-8

"""
    NFVO Module Service

    NFVO module service for the NI project.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.assignment import Assignment  # noqa: E501
from swagger_client.rest import ApiException


class TestAssignment(unittest.TestCase):
    """Assignment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssignment(self):
        """Test Assignment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.assignment.Assignment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
