# coding: utf-8

"""
    NFVO Module Service

    NFVO module service for the NI project.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.actions_api import ActionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestActionsApi(unittest.TestCase):
    """ActionsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.actions_api.ActionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_deploy_vnf(self):
        """Test case for deploy_vnf

        Instantiate an instance of a VNF flavor on a given node.  # noqa: E501
        """
        pass

    def test_set_route(self):
        """Test case for set_route

        Route a request via the provided route.  # noqa: E501
        """
        pass

    def test_shutdown_vnf(self):
        """Test case for shutdown_vnf

        Shut down a VNF instance.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
